name: NetCore
main: de.jakob.netcore.spigot.NetCore
version: 1.0.0
api-version: 1.21
author: EinfachJaakob
load: STARTUP
softdepend: ["PlaceholderAPI", "LuckPerms"]
commands:
  netcore:
    description: "Manage NetCore"